POST http://localhost:4000/app/request
Content-Type: application/json

{
    "requestId": "id1",
    "userId": "id2",
    "amount": 999,
    "title": "donateTest",
    "reason": "test",
    "description": "test"
} 