POST http://localhost:4000/app/signup
Content-Type: application/json

{
    "fullName": "Keith",
    "userName": "donationAddress-kz",
    "email": "k@mail.com",
    "password": "ethwallet",
    "donationAddress": ["acc1"],
    "donateTo": [["acc2", 999]],
    "donateAddress": "addr1"
}