POST http://localhost:4000/app/make-a-donation
Content-Type: application/json

{
    "userId": "624b29c5515812b346cab53e",
    "receiver": "0xd8128c10Cc383797E875DBA2cD3405f07F83d26C",
    "amount": 3,
    "donor_name": "ethwallet"
}