POST http://localhost:4000/app/request
Content-Type: application/json

{
    "user_email": "testrepppoir@what.com",
    "requester_name": "Lee",
    "title": "Veteran Comunity Seeking Help",
    "description": "Condimentum eget sed id justo tincidunt fames. Porttitor odio quam est, nec. Venenatis viverra aliquet sit accumsan penatibus ultricies ultrices at ut. Aliquet amet, a, arcu purus egestas mauris, enim, amet. Condimentum eget sed id justo tincidunt fames. Porttitor odio quam est, nec. Venenatis viverra aliquet sit accumsan penatibus ultricies ultrices at ut. Aliquet amet, a, arcu purus egestas mauris, enim, amet. ",
    "target_amount": 100,
    "vendor_name": "Veteran's House",
    "vendor_email": "test11@gmail.com"
} 